 <div id="header">
  <h1>@ <a href="http://mail-scanning.com/">Mail-Scanning.com</a><span> Fully managed SPAM protection</span></h1>
 </div>
 <div class="navigation">
  <ul>
   <li><a href="http://mail-scanning.com/about/">About</a></li>
   <li><a href="http://mail-scanning.com/documentation/">Documentation</a></li>
   <li><a href="http://mail-scanning.com/faq/">FAQ</a></li>
   <li><a href="http://mail-scanning.com/pricing/">Pricing</a></li>
   <li><a href="http://mail-scanning.com/support/">Support</a></li>
  </ul>
 </div>
