<div class="box" >
<h2>About This Site</h2>
<p>This is a simple blog relating to Debian &amp; Free Software issues.</p>
<ul>
<li><a href="http://debian-administration.org/">Debian Administration</a></li>
<li><a href="http://www.steve.org.uk/">My Website</a></li>
<li><a href="http://mail-scanning.com/">Anti Spam Filtering</a></li>
<li><a href="http://www.steve.org.uk/contact/">Get In Touch</a></li>
</ul>
</div>
